### PR TITLE
add linptech mesh switch and loock classic 2X pro

### PR DESCRIPTION
**Pull request by baiuu**

### CODE REVIEW

**Comment by AlexxIT** [comment]
Are you sure Linptech is Mesh devices? Do you test them with this changes?

**Comment by baiuu** [comment]
> Are you sure Linptech is Mesh devices? Do you test them with this changes?

yes this is Mesh devices xiaomi new devices yes  i test

**Comment by baiuu** [comment]
> Are you sure Linptech is Mesh devices? Do you test them with this changes?

it's Bluetooth Mesh  wireless  switch

**Comment by baiuu** [comment]
> > Are you sure Linptech is Mesh devices? Do you test them with this changes?
> 
> it's Bluetooth Mesh wireless switch

**Pull request closed without merging**
