### PR TITLE
Implement effect_list for pmfbj lights

### PR DESCRIPTION
**Pull request by JonathanKang**

### CODE REVIEW

**Comment by AlexxIT** [comment]
Why you using mode and effect simultaneously?

**Comment by JonathanKang** [comment]
> Why you using mode and effect simultaneously?

The ` MapConv("mode", "select"...` is for creating a select entity for selecting light effects. As effect_list has been implemented, this is not necessary. I'll remove this.

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.5

**Pull request merged**
