### PR TITLE
Fix error in HA 2024.1 (HA>=2023.1)

### LINKED ISSUE #1245: Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
Since the latest core update (2024.1.0b0), I get:
```
2023-12-28 15:16:01.463 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.xiaomi_gateway3.climate
2023-12-28 15:16:01.486 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'xiaomi_gateway3.climate': Platform not found (Exception importing custom_components.xiaomi_gateway3.climate).
```

I had no issue before the update (12 different devices working well)

### PR DESCRIPTION
**Pull request by Necroneco**
Replaced deprecated constants.

https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation

This will increase the minimum HA version requirement to 2023.1

Fix #1245

### CODE REVIEW

**Comment by Glowar** [comment]
Все датчики температуры после обновления перестали работать

**Comment by LeandroIssa** [comment]
@AlexxIT please look at this pull request!

**Review by osigida — APPROVED** [review]

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.5

**Pull request merged**
