### PR TITLE
Add Aqara triple wall switch E1

### PR DESCRIPTION
**Pull request by dixon777**
Tested environment:
HA core: 2023.3.6
HA Frontend: 20230309.1

### CODE REVIEW

**Comment by AlexxIT** [comment]
Can you provide some logs with `mi="6.p.3"` messages? It's better to write tests on this converter

**Comment by dixon777** [comment]
> Can you provide some logs with `mi="6.p.3"` messages? It's better to write tests on this converter

### Logs:
#### MiHome set 'end' to 09:07
```
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] zigbee/recv b'{"cmd":"write","did":"lumi.54ef44100062f7e4","id":25136,"mi_spec":[{"piid":3,"siid":6,"value":118030358}],"source":"","time":1681447084919}'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/commands b'{"commands":[{"commandcli":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 16 00 09 07}","postDelayMs":0},{"commandcli":"send 0x5c65 1 1","postDelayMs":0}]}'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"write_rsp","id":25136,"time":1681447084936,"did":"lumi.54ef44100062f7e4","mi_spec":[{"siid":6,"piid":3,"code":0}]}'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] log/z3 b'Handling Commands Message: {"commands":[{"commandcli":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 16 00 09 07}","postDelayMs":0},{"commandcli":"send 0x5c65 1 1","postDelayMs":0}]}'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] log/z3 b'Msg: clus 0xFCC0, cmd 0x01, len 14'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] log/z3 b'buffer: 15 5F 11 7C 01 08 06 03 01 04 16 00 09 07 '
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] log/z3 b'CLI command executed: raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 16 00 09 07}'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/executed b'{"command":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 16 00 09 07}"}'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessagePreSentCallback b'{"eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x5A","APSPlayload":"0x155F117C01080603010416000907"}'
2023-04-14 04:38:05 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 0x5c65 send {'endpoint': 1, 'seq': 124, 'cluster': 'manufacturer_specific', 'command_id': 1, 'value': b'\x08\x06\x03\x01\x04\x16\x00\t\x07'}
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/executed b'{"command":"send 0x5c65 1 1"}'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] log/z3 b'CLI command executed: send 0x5c65 1 1'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessageReceived b'{"sourceAddress":"0x5C65","eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x3E","APSPlayload":"0x1D5F117C010406030000","rssi":-78,"linkQuality":88}'
2023-04-14 04:38:05 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 (0x5c65) recv {'endpoint': 1, 'seq': 124, 'cluster': 'manufacturer_specific', 'command_id': 1, 'value': b'\x04\x06\x03\x00\x00'}
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] log/z3 b''
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] log/z3 b'T2BCC05AD:RX len 10, ep 01, clus 0xFCC0 (Unknown clus. [0xFCC0]) mfgId 115F FC 1D seq 7C cmd 01 payload[04 06 03 00 00 ]'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessageReceived b'{"sourceAddress":"0x5C65","eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x3F","APSPlayload":"0x1D5F11CD03080603010416000907","rssi":-79,"linkQuality":84}'
2023-04-14 04:38:05 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 (0x5c65) recv {'endpoint': 1, 'seq': 205, 'cluster': 'manufacturer_specific', 'command_id': 3, 'value': b'\x08\x06\x03\x01\x04\x16\x00\t\x07'}
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] log/z3 b''
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] log/z3 b'T2BCC05AD:RX len 14, ep 01, clus 0xFCC0 (Unknown clus. [0xFCC0]) mfgId 115F FC 1D seq CD cmd 03 payload[08 06 03 01 04 16 00 09 07 ]'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"report","id":2000013971,"did":"lumi.54ef44100062f7e4","dev_src":"0","time":1681447085116,"rssi":-66,"mi_spec":[{"siid":6,"piid":3,"value":118030358}]}'
2023-04-14 04:38:05 [D] 192.168.1.6 [LUMI] 0x54ef44100062f7e4 (0x5c65) recv {'led_no_disturb_start': '22:00', 'led_no_disturb_end': '09:07'}
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] miio/report b'{"id":43691613,"method":"properties_changed","params":[{"did":"528382665","piid":3,"siid":6,"value":118030358}]}'
2023-04-14 04:38:05 [D] 192.168.1.6 [MQTT] miio/report_ack b'{"id":43691613,"result":"ok"}'
2023-04-14 04:38:06 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/heartbeat b'{"networkUp":true,"networkPanId":"0x8583","radioTxPower":12,"radioChannel":20,"Directory":"/data/zigbee_host/"}'
```

#### MiHome set 'end' to 23:03
```
2023-04-14 04:38:09 [D] 192.168.1.6 [MQTT] zigbee/recv b'{"cmd":"write","did":"lumi.54ef44100062f7e4","id":25137,"mi_spec":[{"piid":3,"siid":6,"value":118031127}],"source":"","time":1681447089198}'
2023-04-14 04:38:09 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"report","id":25136,"did":"lumi.54ef44100062f7e4","dev_src":"ignore","time":1681447089216,"rssi":-66,"params":[{"piid":3,"siid":6,"value":118030358}]}'
2023-04-14 04:38:09 [D] 192.168.1.6 [LUMI] 0x54ef44100062f7e4 (0x5c65) recv {'led_no_disturb_start': '22:00', 'led_no_disturb_end': '09:07'}
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/commands b'{"commands":[{"commandcli":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 17 03 09 07}","postDelayMs":0},{"commandcli":"send 0x5c65 1 1","postDelayMs":0}]}'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"write_rsp","id":25137,"time":1681447089217,"did":"lumi.54ef44100062f7e4","mi_spec":[{"siid":6,"piid":3,"code":0}]}'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] log/z3 b'Handling Commands Message: {"commands":[{"commandcli":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 17 03 09 07}","postDelayMs":0},{"commandcli":"send 0x5c65 1 1","postDelayMs":0}]}'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/executed b'{"command":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 17 03 09 07}"}'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] log/z3 b'Msg: clus 0xFCC0, cmd 0x01, len 14'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] log/z3 b'buffer: 15 5F 11 7D 01 08 06 03 01 04 17 03 09 07 '
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] log/z3 b'CLI command executed: raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 17 03 09 07}'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessagePreSentCallback b'{"eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x5B","APSPlayload":"0x155F117D01080603010417030907"}'
2023-04-14 04:38:10 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 0x5c65 send {'endpoint': 1, 'seq': 125, 'cluster': 'manufacturer_specific', 'command_id': 1, 'value': b'\x08\x06\x03\x01\x04\x17\x03\t\x07'}
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/executed b'{"command":"send 0x5c65 1 1"}'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] log/z3 b'CLI command executed: send 0x5c65 1 1'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessageReceived b'{"sourceAddress":"0x5C65","eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x40","APSPlayload":"0x1D5F117D010406030000","rssi":-79,"linkQuality":84}'
2023-04-14 04:38:10 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 (0x5c65) recv {'endpoint': 1, 'seq': 125, 'cluster': 'manufacturer_specific', 'command_id': 1, 'value': b'\x04\x06\x03\x00\x00'}
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] log/z3 b''
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] log/z3 b'T2BCC05B1:RX len 10, ep 01, clus 0xFCC0 (Unknown clus. [0xFCC0]) mfgId 115F FC 1D seq 7D cmd 01 payload[04 06 03 00 00 ]'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] log/z3 b''
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] log/z3 b'T2BCC05B1:RX len 14, ep 01, clus 0xFCC0 (Unknown clus. [0xFCC0]) mfgId 115F FC 1D seq 5C cmd 03 payload[08 06 03 01 04 17 03 09 07 ]'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessageReceived b'{"sourceAddress":"0x5C65","eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x41","APSPlayload":"0x1D5F115C03080603010417030907","rssi":-79,"linkQuality":84}'
2023-04-14 04:38:10 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 (0x5c65) recv {'endpoint': 1, 'seq': 92, 'cluster': 'manufacturer_specific', 'command_id': 3, 'value': b'\x08\x06\x03\x01\x04\x17\x03\t\x07'}
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"report","id":2000013972,"did":"lumi.54ef44100062f7e4","dev_src":"0","time":1681447089476,"rssi":-66,"mi_spec":[{"siid":6,"piid":3,"value":118031127}]}'
2023-04-14 04:38:10 [D] 192.168.1.6 [LUMI] 0x54ef44100062f7e4 (0x5c65) recv {'led_no_disturb_start': '23:03', 'led_no_disturb_end': '09:07'}
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] miio/report b'{"id":43691615,"method":"properties_changed","params":[{"did":"528382665","piid":3,"siid":6,"value":118031127}]}'
2023-04-14 04:38:10 [D] 192.168.1.6 [MQTT] miio/report_ack b'{"id":43691615,"result":"ok"}'
```


#### HA set 'end' to 10:21
```
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] zigbee/recv b'{"mi_spec":[{"siid":6,"piid":3,"value":352977687}],"cmd":"write","did":"lumi.54ef44100062f7e4"}'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"report","id":25137,"did":"lumi.54ef44100062f7e4","dev_src":"ignore","time":1681447112796,"rssi":-66,"params":[{"piid":3,"siid":6,"value":118031127}]}'
2023-04-14 04:38:33 [D] 192.168.1.6 [LUMI] 0x54ef44100062f7e4 (0x5c65) recv {'led_no_disturb_start': '23:03', 'led_no_disturb_end': '09:07'}
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/commands b'{"commands":[{"commandcli":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 17 03 0a 15}","postDelayMs":0},{"commandcli":"send 0x5c65 1 1","postDelayMs":0}]}'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"write_rsp","id":0,"time":1681447112797,"did":"lumi.54ef44100062f7e4","mi_spec":[{"siid":6,"piid":3,"code":0}]}'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] log/z3 b'Handling Commands Message: {"commands":[{"commandcli":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 17 03 0a 15}","postDelayMs":0},{"commandcli":"send 0x5c65 1 1","postDelayMs":0}]}'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] log/z3 b'buffer: 15 5F 11 7E 01 08 06 03 01'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] log/z3 b'buffer: 15 5F 11 7E 01 08 06 03 01 04 17 03 0A 15 '
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] log/z3 b'CLI command executed: raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 17 03 0a 15}'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/executed b'{"command":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 17 03 0a 15}"}'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessagePreSentCallback b'{"eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x5C","APSPlayload":"0x155F117E01080603010417030A15"}'
2023-04-14 04:38:33 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 0x5c65 send {'endpoint': 1, 'seq': 126, 'cluster': 'manufacturer_specific', 'command_id': 1, 'value': b'\x08\x06\x03\x01\x04\x17\x03\n\x15'}
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/executed b'{"command":"send 0x5c65 1 1"}'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] log/z3 b'CLI command executed: send 0x5c65 1 1'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessageReceived b'{"sourceAddress":"0x5C65","eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x42","APSPlayload":"0x1D5F117E010406030000","rssi":-78,"linkQuality":88}'
2023-04-14 04:38:33 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 (0x5c65) recv {'endpoint': 1, 'seq': 126, 'cluster': 'manufacturer_specific', 'command_id': 1, 'value': b'\x04\x06\x03\x00\x00'}
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] log/z3 b''
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] log/z3 b'T2BCC05C9:RX len 10, ep 01, clus 0xFCC0 (Unknown clus. [0xFCC0]) mfgId 115F FC 1D seq 7E cmd 01 payload[04 06 03 00 00 ]'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessageReceived b'{"sourceAddress":"0x5C65","eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x43","APSPlayload":"0x1D5F11D503080603010417030A15","rssi":-79,"linkQuality":84}'
2023-04-14 04:38:33 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 (0x5c65) recv {'endpoint': 1, 'seq': 213, 'cluster': 'manufacturer_specific', 'command_id': 3, 'value': b'\x08\x06\x03\x01\x04\x17\x03\n\x15'}
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] log/z3 b''
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] log/z3 b'T2BCC05C9:RX len 14, ep 01, clus 0xFCC0 (Unknown clus. [0xFCC0]) mfgId 115F FC 1D seq D5 cmd 03 payload[08 06 03 01 04 17 03 0A 15 ]'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"report","id":2000013973,"did":"lumi.54ef44100062f7e4","dev_src":"0","time":1681447113017,"rssi":-66,"mi_spec":[{"siid":6,"piid":3,"value":352977687}]}'
2023-04-14 04:38:33 [D] 192.168.1.6 [LUMI] 0x54ef44100062f7e4 (0x5c65) recv {'led_no_disturb_start': '23:03', 'led_no_disturb_end': '10:21'}
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] miio/report b'{"id":43691617,"method":"properties_changed","params":[{"did":"528382665","piid":3,"siid":6,"value":352977687}]}'
2023-04-14 04:38:33 [D] 192.168.1.6 [MQTT] miio/report_ack b'{"id":43691617,"result":"ok"}'
```



#### HA set 'start' to 00:02
```
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] zigbee/recv b'{"mi_spec":[{"siid":6,"piid":3,"value":352977408}],"cmd":"write","did":"lumi.54ef44100062f7e4"}'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"report","id":0,"did":"lumi.54ef44100062f7e4","dev_src":"ignore","time":1681447125256,"rssi":-66,"params":[{"siid":6,"piid":3,"value":352977408}]}'
2023-04-14 04:38:46 [D] 192.168.1.6 [LUMI] 0x54ef44100062f7e4 (0x5c65) recv {'led_no_disturb_start': '00:02', 'led_no_disturb_end': '10:21'}
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/commands b'{"commands":[{"commandcli":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 00 02 0a 15}","postDelayMs":0},{"commandcli":"send 0x5c65 1 1","postDelayMs":0}]}'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"write_rsp","id":0,"time":1681447125257,"did":"lumi.54ef44100062f7e4","mi_spec":[{"siid":6,"piid":3,"code":0}]}'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] log/z3 b'Handling Commands Message: {"commands":[{"commandcli":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 00 02 0a 15}","postDelayMs":0},{"commandcli":"send 0x5c65 1 1","postDelayMs":0}]}'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] log/z3 b'buffer: 15 5F 11 7F 01 08 06 03 01'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] log/z3 b'buffer: 15 5F 11 7F 01 08 06 03 01 04 00 02 0A 15 '
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] log/z3 b'CLI command executed: raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 00 02 0a 15}'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/executed b'{"command":"raw 0xfcc0 {15 5f 11 00 01 08 06 03 01 04 00 02 0a 15}"}'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessagePreSentCallback b'{"eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x5D","APSPlayload":"0x155F117F01080603010400020A15"}'
2023-04-14 04:38:46 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 0x5c65 send {'endpoint': 1, 'seq': 127, 'cluster': 'manufacturer_specific', 'command_id': 1, 'value': b'\x08\x06\x03\x01\x04\x00\x02\n\x15'}
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/executed b'{"command":"send 0x5c65 1 1"}'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] log/z3 b'CLI command executed: send 0x5c65 1 1'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessageReceived b'{"sourceAddress":"0x5C65","eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x44","APSPlayload":"0x1D5F117F010406030000","rssi":-79,"linkQuality":84}'
2023-04-14 04:38:46 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 (0x5c65) recv {'endpoint': 1, 'seq': 127, 'cluster': 'manufacturer_specific', 'command_id': 1, 'value': b'\x04\x06\x03\x00\x00'}
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] log/z3 b''
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] log/z3 b'T2BCC05D5:RX len 10, ep 01, clus 0xFCC0 (Unknown clus. [0xFCC0]) mfgId 115F FC 1D seq 7F cmd 01 payload[04 06 03 00 00 ]'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] gw/50EC505302019CFC/MessageReceived b'{"sourceAddress":"0x5C65","eui64":"0x54EF44100062F7E4","destinationEndpoint":"0x01","clusterId":"0xFCC0","profileId":"0x0104","sourceEndpoint":"0x01","APSCounter":"0x45","APSPlayload":"0x1D5F110603080603010400020A15","rssi":-78,"linkQuality":88}'
2023-04-14 04:38:46 [D] 192.168.1.6 [ZIGB] 0x54ef44100062f7e4 (0x5c65) recv {'endpoint': 1, 'seq': 6, 'cluster': 'manufacturer_specific', 'command_id': 3, 'value': b'\x08\x06\x03\x01\x04\x00\x02\n\x15'}
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] log/z3 b''
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] log/z3 b'T2BCC05D5:RX len 14, ep 01, clus 0xFCC0 (Unknown clus. [0xFCC0]) mfgId 115F FC 1D seq 06 cmd 03 payload[08 06 03 01 04 00 02 0A 15 ]'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] zigbee/send b'{"cmd":"report","id":2000013974,"did":"lumi.54ef44100062f7e4","dev_src":"0","time":1681447125496,"rssi":-66,"mi_spec":[{"siid":6,"piid":3,"value":352977408}]}'
2023-04-14 04:38:46 [D] 192.168.1.6 [LUMI] 0x54ef44100062f7e4 (0x5c65) recv {'led_no_disturb_start': '00:02', 'led_no_disturb_end': '10:21'}
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] miio/report b'{"id":43691619,"method":"properties_changed","params":[{"did":"528382665","piid":3,"siid":6,"value":352977408}]}'
2023-04-14 04:38:46 [D] 192.168.1.6 [MQTT] miio/report_ack b'{"id":43691619,"result":"ok"}'
```
### Validation script:
```
# Extracted from class AqaraLedNoDisturbTimeConv in custom_components/xiaomi_gateway3/core/converters/base.py
map = {
    (h | (m << 8)): f"{h:02d}:{m:02d}" for h in range(24) for m in range(60)
}
reversed_map = {
    f"{h:02d}:{m:02d}":(h | (m << 8)) for h in range(24) for m in range(60)
} 

def _decode_start(encoded):
    return encoded & 0xFFFF

def _decode_end(encoded):
    return (encoded >> 16) & 0xFFFF

# END Extraction

# For validation
def print_start_end_time(encoded):
    start_time = _decode_start(encoded)
    end_time = _decode_end(encoded)
    print(f"{map[start_time]} - {map[end_time]}")

print_start_end_time(118030358) # 22:00 - 09:07
print_start_end_time(118031127) # 23:03 - 09:07
print_start_end_time(352977687) # 23:03 - 10:21
print_start_end_time(352977408) # 00:02 - 10:21
```

**Comment by AlexxIT** [comment]
Thanks! I reworked your code. Instead of drop-down lists, I made it with text input. This way, in my opinion, is simpler.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.0

**Pull request merged**
