### PR TITLE
Add new BLE device: Qingping Temp & RH Monitor

### PR DESCRIPTION
**Pull request by kamingchan**
https://www.qingping.co/temp-rh-monitor/specifications

image

### CODE REVIEW

**Review by AlexxIT — APPROVED** [review]

**Comment by AlexxIT** [comment]
Maybe it is https://a.aliexpress.com/_vTa1mv ?
Because 982 also CGH1

**Comment by AlexxIT** [comment]
Do you have box with right model?

**Comment by kamingchan** [comment]
IMG_0302

It's not `CGH1` but `CGG1`.

**Comment by kamingchan** [comment]
image

**Pull request merged**
