### PR TITLE
Adapt to Home Assistant 2023.1.0b0+ 

### PR DESCRIPTION
**Pull request by piio**
Resolve https://github.com/AlexxIT/XiaomiGateway3/issues/899

### CODE REVIEW

**Comment by dscao** [comment]
This is ok for ha 2023.1.0

**Comment by brucewzp** [comment]
it works,thanks!

**Comment by MackoMici** [comment]
it works,thanks!

**Comment by iNowack** [comment]
Adoption is working with
  Home Assistant 2023.1.0
  Supervisor 2022.12.1
  Operating System 9.4
  Frontend 20230104.0 - latest
THANKS

**Comment by AlexxIT** [comment]
Closed because without backward compatibility with old Hass versions

**Pull request closed without merging**
