### PR TITLE
add support for Linptech Wireless Button KS1Pro BLE KS1PBB

### PR DESCRIPTION
**Pull request by jwxa**
new device which is not found in home.miot-spec.com at the moment
IMG_20231203_151641
b727e3ef3ee9fbea03a6ce519f8b9c26
image

tested on Xiaomi Multimode Gateway (CN)  ZNDMWG03LM
FIRMWARE........: 1.5.0_0102 #20210816
and homeassistant docker image: homeassistant/home-assistant:2023.10

### CODE REVIEW

**Comment by jwxa** [comment]
```yaml
alias: Linptech KS1Pro auto
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.a4c1388527aa_action
    to: button_1_single
condition: []
action:
  - service: light.toggle
    data: {}
    target:
      device_id: bebd7f8cb091fca10e4ff3ba6109d4d5
mode: single
```
automation example

**Comment by AlexxIT** [comment]
Thanks! But this spec won't work on new gateway firmwares. Will work only on old firmwares like yours.

**Comment by AlexxIT** [comment]
Yes. Check this specs examples
https://github.com/AlexxIT/XiaomiGateway3/blob/0707fc1ced0358dee60fc80a7524e0f83ff696f2/custom_components/xiaomi_gateway3/core/converters/devices.py#L1248

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.5

**Pull request merged**
