### PR TITLE
Add LAN MAC to Multimode Gateway 2 device entry

### PR DESCRIPTION
**Pull request by geom100**
MGW2 reports wlan0 mac address irrespective to real connection type. It is not comfortable when connecting gateway over ethernet. The patch returns mac address of telnet connection used to control MGW2. All entities are created with useful ids. It works for my gateway.

### CODE REVIEW

**Comment by AlexxIT** [comment]
I don't think this is good idea because wlan mac used as unique ID. If user changes gateway connection type - all entities will be duplicate.

You can change entity_id manually. It's not a problem. And it is possible to write support for displaying the active MAC address in the interface. But I think the unique gateway ID should always be the same, no matter what type of connection.

I have the request with support both types simultaneously. But this is not easy task.
https://github.com/AlexxIT/XiaomiGateway3/issues/1013

**Comment by geom100** [comment]
Thank your for reply!
I have Keenetic NDMS2 integration installed for device tracking. When I add Xiaomi Gateway integration as well and restart HA, entities from Keenetic and Xiaomi integrations become somehow linked in wrong way.
First, I add my Xiaomi gateway, it creates the following entities:
mgw2-1
Then I restart HA instance and see the following in binary_sensor.54efxxxxxxxx_gateway properties:
mgw2-2
And in Xiaomi Gateway device properties:
mgw2-3

I also tried to manually change entity names to reflect eth0 MAC right after I've added Xiaomi integration, before restar:
mgw2-4
But after I restart HA instance device is still linked to 54:EF:xxxx entities from Keenetic and I see the same second and third pictures.

The problem is not critical for now, but is annoying. I know my patch is not bright, but it allows entities from different integrations to be linked correctly when gateway is initially connected via eth0. As far as I know, there is no way to switch to WiFi other then reset device, so it anyway needs to be re-added to HA.

If you have an idea why and how entities from different integrations become linked, please let me know where can I look for code implementing this linking. Maybe I can find more elegant solution.

**Comment by AlexxIT** [comment]
Device can have multiple MAC. It's not a problem. Just need to implement this situation
https://github.com/AlexxIT/XiaomiGateway3/blob/cdd153be49e600712494c60ee45ec1db204efa40/custom_components/xiaomi_gateway3/core/entity.py#L318-L341

**Comment by geom100** [comment]
Thank you very much! I will try to experiment with it.

**Comment by geom100** [comment]
I've made some changes according to your advise. It works much better then my original patch.
mgw2-5
There is no change to unique ID mac address anymore. Instead, alternative mac addresses can be added to XDevice. mac argument to \__init\__ method accepts either string primary mac address or tuple of (primary mac, Set[alternative macs]). So API of XDevice is not changed from its clients perspective. Alternative mac addresses are added to entity connections set if they are valid.

**Comment by AlexxIT** [comment]
Thanks! I took your ideas, but reworked the code a bit. To make it simpler.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.0

**Pull request closed without merging**
