### PR TITLE
feat: support button click action in wireless mode for  DHKG01ZM,ZNKG01HL,ZNKG02HL and ZNKG03HL

### PR DESCRIPTION
**Pull request by TioaChan**
see https://github.com/AlexxIT/XiaomiGateway3/issues/579 & https://github.com/AlexxIT/XiaomiGateway3/issues/467

image
image
all works fine.

### CODE REVIEW

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
I wonder why 1945 don't have wireless switch.

**Comment by TioaChan** [comment]
> I wonder why 1945 don't have wireless switch?

 https://github.com/AlexxIT/XiaomiGateway3/pull/725

**Comment by xinyuan-liu** [comment]
Hello @TioaChan, I didn't find the botton in the entity list and cannot set any botton action.

My device is ZNKG03HL.

image

image

**Comment by TioaChan** [comment]
Upgrade your component version.

xinyuan liu ***@***.***>于2022年8月3日 周三01:04写道：

**Pull request merged**
