### PR TITLE
Add support Xiaomi Smart Hub 2 Pro

### PR DESCRIPTION
**Pull request by niceboygithub**
Add support of Xiaomi Smart Hub 2 Pro

### CODE REVIEW

**Comment by AlexxIT** [comment]
Wow. Thanks! I'm waiting it. Already ordered.

**Comment by niceboygithub** [comment]
Lumi adds some protections.

If mosquitto run as public, the new zigbee devices can not join. That's my local test.
So if want to use hub v2 in HA, it needs paring all zigbee devices then add the hub v2 to HA.

**Comment by sumsethan** [comment]
no entity shows after adding new gateway 

log says “Can't prepare gateway”


`2022-09-13 16:03:42.784 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.gateway] 172.16.10.41 | Can't prepare gateway
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/streams.py", line 617, in readuntil
await self._wait_for_data('readuntil')
File "/usr/local/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
await self._waiter
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
return fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/gateway/__init__.py", line 168, in prepare_gateway
sh = await session.login()
File "/config/custom_components/xiaomi_gateway3/core/shell/__init__.py", line 46, in login
await shell.login()
File "/config/custom_components/xiaomi_gateway3/core/shell/shell_hubv2.py", line 44, in login
await asyncio.wait_for(coro, timeout=3)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError`

tried telnet to gw, with open telnet command, port 23 is open but can't connect with user "admin" and empty password,

maybe that's why  “Can't prepare gateway”?
is there any new "open telnet command" needed?


thx for your wonderful work anyway

**Comment by AlexxIT** [comment]
@sumsethan what firmware does your hub have?

**Comment by niceboygithub** [comment]
The user is “root”

The command is 
```

{"method":"set_ip_info","params":{"ssid":"\"\"","pswd":"123123 ; passwd -d root; /bin/riu_w 101e 53 3012; telnetd"}}

```

**Comment by niceboygithub** [comment]
You need make sure that the gateway and ha are in the same domain.

**Comment by sumsethan** [comment]
> You need make sure that the gateway and ha are in the same domain.

yes they are in a same subnet,
with your open telnet command it works and can show zigbee devices,
but some how ble and ble mesh devices not shown,
maybe that's because i've got a Xiaomi Hub Gateway 4 (ZSWG01CM) in my iot network so all ble devices are managed by it?

**Comment by sumsethan** [comment]
> @sumsethan what firmware does your hub have?

It's  1.0.3_0028，with the new offerd open telnet command above ,it works~

**Comment by niceboygithub** [comment]
> > You need make sure that the gateway and ha are in the same domain.
> 
> yes they are in a same subnet, with your open telnet command it works and can show zigbee devices, but some how ble and ble mesh devices not shown, maybe that's because i've got a Xiaomi Hub Gateway 4 (ZSWG01CM) in my iot network so all ble devices are managed by it?

The ble of hub v2 in this XG3 integration is not supported yet.
It needs other experts, like Alex to coding.
Please stay tuned, Alex is waiting for his hub v2.

**Comment by niceboygithub** [comment]
Another issue was found.
Please do not enable stats of zigbee, otherwise the Hub V2 will disfunction with zigbee devices.

**Comment by sumsethan** [comment]
> Another issue was found. Please do not enable stats of zigbee, otherwise the Hub V2 will disfunction with zigbee devices.

noticed that...

looking forward to Alex's great works

**Comment by tufeikafei** [comment]
I found a problem with the new fw version.Today it hub auto update to 1.0.6_0004,and it not works.

**Comment by DJTerentjev** [comment]
> Another issue was found. Please do not enable stats of zigbee, otherwise the Hub V2 will disfunction with zigbee devices.

Yes my Xiaomi relays stop working if statistics is on. But if I understand correctly without statistic third party devices will not work.

**Comment by AlexxIT** [comment]
3rd party zigbee devices don't depends on statistics function

**Comment by DJTerentjev** [comment]
I tried to connect Philips Hue motion sensor  9290019758 by modifying converter. Sensor is identical to 9290012607 just model is different. But I got data only once while pairing. Unfortunately I don't have other supported devises . Is anyone successfully connect 3rd  party devises with Hub 2?

**Pull request merged**
