### PR TITLE
feat: Add Loock Smart Lock V5 Max (model loock.lock.fcl201)

### PR DESCRIPTION
**Pull request by meteoral**
add support for Loock Smart Lock V5 Max, spec herf: https://home.miot-spec.com/s/loock.lock.fcl201

image

### CODE REVIEW

**Comment by AlexxIT** [comment]
Can you fix `method`? It has different styles of writing values.

**Comment by meteoral** [comment]
> Can you fix `method`? It has different styles of writing values.

sure
FIXED

**Review by AlexxIT — APPROVED** [review]

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
Related issue https://github.com/AlexxIT/XiaomiGateway3/issues/1455

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.7

**Pull request merged**
