### PR TITLE
Add initial support for Mesh switches

### PR DESCRIPTION
**Pull request by hellkun**
I've bought some mesh wall switches recently, which looks quite simliar with Aqara ones, but they communicate with the gateway via Bluetooth Mesh rather than Zigbee, one example would be the device I mentioned in #95.

I try to add support for those mesh switches, and it works with:
+ Model 2007 (basically a single relay) 
+ Model 2257 (a wall switch with 2 buttons and backlight)

More models shall be added once I get their debug logs.

### CODE REVIEW

**Comment by itispip** [comment]
I just modified the components and added support for Switch. The Switch I am using is model 3015 and 2027, but I am very sure any switch following MI IoT spec can work (just need add the model name into support list, no need for coding), or I can further change the code to default any model with 4 digits as Switch.  I just don't know how to submit my code to AlexxIT

**Comment by hellkun** [comment]
> I just modified the components and added support for Switch. The Switch I am using is model 3015 and 2027, but I am very sure any switch following MI IoT spec can work (just need add the model name into support list, no need for coding), or I can further change the code to default any model with 4 digits as Switch. I just don't know how to submit my code to AlexxIT

Actually it varies from model to model. Models use a combination of Service ID and Property ID for each function, and the acceptable values for the combination vary too . What you said might work pretty well for simple devices, like single-key switches, but not for 'complex' devices. Take this PR for example, model 2257 (a dual-key wall switch) provides 5 different functions (left/right keys, left/right key always-on, backlight), in other words, takes 5 different combinations of siid and piid to query and control.
A light device is usually about ONE entity with multiple attributes. However, for switches, it might be a good idea to be able to create one or more switch entities from a single device, just what has been done for Aqara multi-key zigbee wall switches.

**Comment by AlexxIT** [comment]
I remember about you, but don't have time to check code and merge yet.

**Comment by hellkun** [comment]
Hi, AlexxIT, I'm aware that you were busy, really appreicate your amazing work on this integration.
I've reworked on this PR, now it's rebased on tag v0.10.4, and I also managed to make less modification to existing code than before, which could be easier to review, hopefully.

**Pull request closed without merging**
