### PR TITLE
Add support for Linptech Submersion Sensor, Pressure Sensor and gdds.light.wy0a01

### PR DESCRIPTION
**Pull request by justbin95**
https://home.miot-spec.com/s/linp.flood.rs1bb
https://home.miot-spec.com/s/linp.senpres.ps1bb

### CODE REVIEW

**Comment by AlexxIT** [comment]
Thanks!

**Comment by ABUAIJUTIE** [comment]
This converter it's not working. Still get unknown after adding it.
I make some modifications like below and move it from the end of device.py (MESH DEVICES part) to BLE part (right below **16143: ["Linptech", "Submersion Sensor", "RS1BB"]** ). And it works.
```
{
    16204: ["Linptech", "Pressure Sensor", "PS1BB"],
    "spec": [
        BoolConv("pressure_state", "binary_sensor", mi="2.p.1060"),  # bool
        Converter("battery", "sensor", mi="3.p.1003"),
    ],
}
```
I'm not sure about converter's location in the device.py file will affect or not, but when this converter was placed at the end of the file, it just failed.

**Comment by Necroneco** [comment]
> This converter it's not working. Still get unknown after adding it. I make some modifications like below and move it from the end of device.py (MESH DEVICES part) to BLE part (right below **16143: ["Linptech", "Submersion Sensor", "RS1BB"]** ). And it works.
> 
> ```
> {
>     16204: ["Linptech", "Pressure Sensor", "PS1BB"],
>     "spec": [
>         BoolConv("pressure_state", "binary_sensor", mi="2.p.1060"),  # bool
>         Converter("battery", "sensor", mi="3.p.1003"),
>     ],
> }
> ```
> 
> I'm not sure about converter's location in the device.py file will affect or not, but when this converter was placed at the end of the file, it just failed.

Agree, this should move before the line  `"default": "ble"`

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.4

**Comment by latel** [comment]
Will next release fix this issue, I've the same problem.

**Pull request merged**
