### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by letovlive**
I have Xiaomi Mijia MJTS003 and they are working properly with your integration

### CODE REVIEW

**Comment by AlexxIT** [comment]
All models take automatically from source code. Which model appears on the device page?

**Comment by letovlive** [comment]
image

**Comment by letovlive** [comment]
image

**Comment by AlexxIT** [comment]
Thanks. Readme is autocreated from sourcecode. I have added this model to bluetooth.py file

**Pull request closed without merging**
