### PR TITLE
partial support for fw 1.5.4_0052

### PR DESCRIPTION
**Pull request by zvldz**

### CODE REVIEW

**Comment by XTR1984** [comment]
on fw 1.5.4_0084, model zndmwg02lm  with this patch  bluetooth sensors works too

**Comment by feelingm** [comment]
I confirm that my Flower Care (ble HHCCJCY01), HT (LYWSDCGQ/01ZM), HT (LYWSD03MMC) work with this codes. Thanks.

**Comment by mihsu81** [comment]
I can confirm ble HHCCJCY01, ble XMWSDJ04MMC and mesh WX10ZM working with the PR from @XTR1984 and firmware 1.5.4_0090

**Comment by wzzyj** [comment]
Can confirm it works for BLE RTCGQ02LM / BLE LYWSD02MMC / ble (735) / mesh (4896) with gateway 1.5.4_0090. Thanks for the great work.

**Comment by GormYa** [comment]
HT LYWSD03MMC work with this codes. Thanks.

**Pull request closed without merging**
