### PR TITLE
add support for device cxw-ble006

### PR DESCRIPTION
**Pull request by nesror**

### CODE REVIEW

**Comment by AlexxIT** [comment]
Thanks! I have rewrited converter into new format. Not sure if `rotate` works fine.

**Comment by AlexxIT** [comment]
For your info https://github.com/AlexxIT/Blog/issues/20

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0

**Comment by relliky** [comment]
@AlexxIT this commit https://github.com/AlexxIT/XiaomiGateway3/commit/208ca11be61b20a2bad701c69b4de99d04a3eb86 does not provide variable knob rotation events as previously provided by https://github.com/AlexxIT/XiaomiGateway3/pull/1303/commits/32c5f2e47e7e184247dbf89998624957f131bbb1

I'd like to push a PR to fix it for the new converter format because I have the device in my hand. The only thing I'd like to know is a way to obtain the property value once I pressed the button or twist the knob. e.g. I can see the previous converter has these values mapped

```
            -11: "knob_reduced_1", -12: "knob_reduced_2", -13: "knob_reduced_3",
            -14: "knob_reduced_4", -15: "knob_reduced_5", -16: "knob_reduced_6",
            -17: "knob_reduced_7", -18: "knob_reduced_8", 
```

I am not sure how @nesror obtain these values as they are not present in the MIOT spec https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:remote-control:0000A021:cxw-ble006:1

**Comment by relliky** [comment]
Never mind. I found the fix and will push a PR.

**Comment by relliky** [comment]
Raised PR https://github.com/AlexxIT/XiaomiGateway3/pull/1352

**Pull request closed without merging**
