### PR TITLE
Fix color and brightness support at light.py

### PR DESCRIPTION
**Pull request by kolegych**
Fix of https://github.com/AlexxIT/XiaomiGateway3/issues/1254

### CODE REVIEW

**Comment by kolegych** [comment]
@AlexxIT could you kindly look at this PR

**Comment by AlexxIT** [comment]
This is outdated variables and shouldn't be used

**Comment by Wh1terat** [comment]
> This is outdated variables and shouldn't be used

True, but whilst moving to LightEntityFeature you've not implemented ColorMode though  - so we lose brightness, color and effects.

**Comment by AlexxIT** [comment]
I know about issue

**Comment by kolegych** [comment]
From my point of view it is better to use deprecated constants instead of loss the functionality. 
Because 3.3.4 don't work with new HA.
But 3.3.5 don't work with Xiaomi light controls.

**Comment by Wh1terat** [comment]
> From my point of view it is better to use deprecated constants instead of loss the functionality. Because 3.3.4 don't work with new HA. But 3.3.5 don't work with Xiaomi light controls.

It's a regression bug for sure; but @AlexxIT 's point is if it needs fixing then it needs fixing right and not just rolling back.

It's not a big fix, at least on the surface. Import ColorMode and declare _attr_supported_color_modes appropriately.

```python3
    def __init__(self, gateway: "XGateway", device: XDevice, conv: Converter):
        super().__init__(gateway, device, conv)
        self._attr_supported_color_modes = set()

        for conv in device.converters:
            if conv.attr == ATTR_BRIGHTNESS:
                self._attr_supported_features |= LightEntityFeature.TRANSITION
                self._attr_supported_color_modes.add(ColorMode.BRIGHTNESS)
            elif conv.attr == ATTR_COLOR_TEMP:
                self._attr_supported_color_modes.add(ColorMode.COLOR_TEMP)
```

**Comment by AlexxIT** [comment]
@Wh1terat Thank you. Been fixing my other projects. Thank you. Been fixing my other projects. A lot of them broke after 2024.1.

Not best solution because docs saes that `supported_color_modes` should be only one for `COLOR_TEMP` or `BRIGHTNESS` or `ONOFF`. Don't know if it really necessary.

https://github.com/AlexxIT/XiaomiGateway3/commit/387256c2c7cb8e46efef30feca4b674255b9aa33

**Pull request closed without merging**
