### PR TITLE
Add devices' support and change cover fix's parameter

### PR DESCRIPTION
**Pull request by micturkey**
I added support for Xiaomi Mesh Neutral Wire version wall switch and LS Smart Curtain Motor.
And as is mention in https://github.com/AlexxIT/XiaomiGateway3/commit/fb0c0300f7a870ace672b22e92d63726d584c760 , set the parameter to 2 may be better 🤣

### CODE REVIEW

**Comment by AlexxIT** [comment]
1. I don't know if cover fix will be suitable for all users. Because it is global fix. Even for Zigbee models. But let it be this way.
2. `device_fault` coverters don't show result anywhere.
3. Cover device shouldn't have separate on switch. What does this converter do with real device?

**Comment by micturkey** [comment]
> 1. I don't know if cover fix will be suitable for all users. Because it is global fix. Even for Zigbee models. But let it be this way.
> 
>     2. `device_fault` coverters don't show result anywhere.
> 
>     3. Cover device shouldn't have separate on switch. What does this converter do with real device?

1. I think this issue may happen on other curtain motors, such as Aqara Curtain Companion E1 (which cannot be added to MiHome). You can check it out in the comment area of https://www.bilibili.com/video/BV1PS4y1E7wk, which says "sometimes the curtain is 100% closed but after a while it turns to 1% open" (窗帘100%闭合后，过段时间会变成 1% 的打开状态). So I think it is a common issue.
2.  Yes, you can just remove that and I really don't understand how to use `map` 😂.
3. This switch is to reverse the motor, which helps to fix the issue when "open" in apps leads to "close" in real. In MiHome app it is called revered mode (反转模式)
IMG_3781(20220727-004059)
.

**Comment by AlexxIT** [comment]
I know what is motor reverse. I'm asking about on switch.
```
Converter("motor_reverse", "switch", mi="2.p.5", enabled=False),
BoolConv("on", "switch", mi="2.p.9"),  
```

**Comment by micturkey** [comment]
> I know what is motor reverse. I'm asking about "on" switch.
> 
> ```
> 
> Converter("motor_reverse", "switch", mi="2.p.5", enabled=False),
> 
> BoolConv("on", "switch", mi="2.p.9"),  
> 
> ```

Sorry I misunderstood your question.
This mesh device does have such switch in its spec which you can check on https://home.miot-spec.com.
I was thinking this switch is not important and so set its enabled=false, but after that the curtain would not work at all.
I think it is a switch deciding whether the curtain is enabled. 
If I don't add this spec in migateway3, will it work? I will check it later.

**Comment by AlexxIT** [comment]
Anyway Thanks a lot!

**Pull request merged**
