### PR TITLE
Add support for Xiaomi hoto.light.lamp

### PR DESCRIPTION
**Pull request by ABUAIJUTIE**
Add support for Xiaomi Mijia Camping Lantern hoto.light.lamp

```
{ 
    # https://home.miot-spec.com/spec/hoto.light.lamp
    9387: ["Xiaomi", "Multifunctional Camping Lantern", "hoto.light.lamp"],
    "spec": [
        BaseConv("light", "light", mi="2.p.1"),
        BrightnessConv("brightness", mi="2.p.2", max=100),
        ColorTempKelvin("color_temp", mi="2.p.3", mink=2700, maxk=5000),
        MathConv("color", "number", mi="2.p.4", min=1, max=16777215),
        MapConv("mode", "select", mi="2.p.5", map={1: "Auto", 2: "Day", 3: "Color", 4: "Warmth", 5: "Leisure"}),
        BaseConv("battery", "sensor", mi="3.p.1"), 
        MapConv("main_ charging_state", "sensor", mi="3.p.2", map={0: "Not Plug", 1: "Plug In"}), 
        MapConv("sub_ charging_state", "sensor", mi="3.p.3", map={0: "No Equipment", 1: "Charging", 2: "Full", 3: "Inserted Without Charge"}), 
        BoolConv("delay_switch", "switch", mi="4.p.1"),
        MathConv("delay_time", "number", mi="4.p.2", min=1, max=60), 
    ],
}, 
```

hoto.light.lamp

### CODE REVIEW

**Review by AlexxIT — APPROVED** [review]

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6

**Comment by swas** [comment]
Hello!

Can you add support for "hoto.light.lamp02"
https://home.miot-spec.com/spec/hoto.light.lamp02

It's the same product but for non CN server:

image


Thanks!!

**Comment by swas** [comment]
Another question

Its possible to get a color picker (with a color wheel) instead of a textbox for selecting colors?


MathConv("color", "number", mi="2.p.4", min=1, max=16777215),

**Comment by AlexxIT** [comment]
I don't have any examples of RGB lamps. If you send multiple logs from your device - I can try to write RGB converter for it.

**Comment by swas** [comment]
Thanks @AlexxIT 

I send you a debug log changing the color of the lamp


The ble mac of the device is: d4f0ea8bdb9b

```
2024-11-20 16:56:24.826 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'write', 'data': {'light': True}}
2024-11-20 16:56:25.257 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'light': True}}
2024-11-20 16:56:25.566 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'sub_ charging_state': 'Charging'}}
2024-11-20 16:56:25.573 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'light': True, 'sub_ charging_state': 'Charging'}}
2024-11-20 16:56:27.447 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'write', 'data': {'brightness': 140}}
2024-11-20 16:56:27.535 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'brightness': 140.25}}
2024-11-20 16:56:38.577 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'write', 'data': {'color': 15095089.0}}
2024-11-20 16:56:38.808 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'color': 15095089}}
2024-11-20 16:56:40.699 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'sub_ charging_state': 'Full'}}
2024-11-20 16:56:58.912 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'light': False}}
2024-11-20 16:57:01.699 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'color': 15288544}}
2024-11-20 16:57:01.848 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'brightness': 2.5500000000000003}}
2024-11-20 16:57:01.878 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'color': 15288544}}
2024-11-20 16:57:02.299 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'light': True}}
2024-11-20 16:57:04.511 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'color': 4843055}}
2024-11-20 16:57:04.745 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'brightness': 2.5500000000000003, 'color': 4843055}}
2024-11-20 16:57:07.869 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'color': 15095854}}
2024-11-20 16:57:10.049 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'write', 'data': {'color': 15095855.0}}
2024-11-20 16:57:10.237 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'color': 15095855}}
2024-11-20 16:57:11.102 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'write', 'data': {'color': 15095856.0}}
2024-11-20 16:57:11.239 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'color': 15095856}}
2024-11-20 16:57:15.419 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'write', 'data': {'light': False}}
2024-11-20 16:57:15.509 DEBUG (MainThread) [custom_components.xiaomi_gateway3.gate.192.168.0.29] {'uid': 'd4f0ea8bdb9b', 'did': '1096235486', 'msg': 'on_report', 'data': {'light': False}}
```

**Comment by AlexxIT** [comment]
Please show how looks like RED color, GREEN color and BLUE color.

**Comment by swas** [comment]
Red: 16711680
Green: 65280 
Blue: 255

It's looks like decimal color

**Comment by AlexxIT** [comment]
Thanks. Let's continue here #1396

**Pull request merged**
