### PR TITLE
Add support for PTX Mesh Single Wall Switch(No N) & frfox.switch.bl02 & frfox.switch.bl03

### PR DESCRIPTION
**Pull request by flyibeat**
add support PTX Mesh Single Wall Switch(No N)：
https://home.miot-spec.com/spec/090615.switch.aidh1

update 
https://home.miot-spec.com/spec/090615.switch.aidh2 
https://home.miot-spec.com/spec/090615.switch.akkw1

### CODE REVIEW

**Comment by flyibeat** [comment]
add support for “frfox.switch.bl02” “frfox.switch.bl03”
https://home.miot-spec.com/spec/frfox.switch.bl02
https://home.miot-spec.com/spec/frfox.switch.bl03

**Comment by flyibeat** [comment]
add support for frfox.switch.bl02 #1140

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.3

**Pull request merged**
